#!/bin/sh

# Clean Index
echo \
'<html>

<script>
    function searchInUL() {
        // Declare variables
        var input, filter, ul, li, a, i, txtValue;
        input = document.getElementById("inputElement");
        filter = input.value.toUpperCase();
        ul = document.getElementById("listRecipes");
        li = ul.getElementsByTagName("li");

        // Loop through all list items, and hide those who dont match the search query
        for (i = 0; i < li.length; i++) {
            a = li[i].getElementsByTagName("a")[0];
            txtValue = a.textContent || a.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }
</script>


<style>
    #inputElement {
        width: 100%;
        font-size: 16px;
        padding: 10px;
    }

    #listRecipes {
        font-size: 18px;
        margin: 0;
        padding: 0;
        text-align: center;
    }
</style>

<body>
    <input type="text" id="inputElement" onkeyup="searchInUL()" placeholder="Search for names..">
    <ul id="listRecipes">' > ./index.html

# Generate index
for f in ./*.md ./.*.md; do
    n="$(basename $f)"
    [ -f "$f" ] &&
    echo '        <li><a href="'"${f%.md}"'">'"${n%.md}"'</a></li>' >> ./index.html
done

# Append closing tags
echo \
'    </ul>
</body>

</html>' >> ./index.html

git add index.html

exit 0
